In [1]:
import numpy as np

In [2]:
A = np.array([[3, 3], 
              [2, 5], 
              [0, 6]])
B_T = np.array([[3, 2, 3], 
                [2, 6, 1]])

In [121]:
def pivoting(tableau, basic_vars, pivot):
    #divide by zero may be encountered
    ratios = np.empty(tableau.shape[0])
    for i in range(tableau.shape[0]):
        if tableau[i, pivot] != 0:
            ratios[i] = tableau[i, -1] / tableau[i, pivot]
        else:
            ratios[i] = 10e9
    #ratios = tableau[:, -1] / tableau[:, pivot]
    row_min = ratios.argmin()
    basic_vars[row_min] = pivot
    tableau[row_min, :] /= tableau[row_min, pivot]
    for i in range(tableau.shape[0]):
        if i != row_min:
            tableau[i, :] -= tableau[i, pivot] * tableau[row_min, :]
    return None

In [122]:
def create_tableau(A, B):
    B_T = B.T
    m, n = A.shape
    tableaus = []
    for i in range(2):
        tableaus.append(np.empty((A.shape[1-i], m+n+1)))
        tableaus[i][:, :m] = [B_T, np.identity(m)][i]
        tableaus[i][:, m:m+n] = [np.identity(n), A][i]
        tableaus[i][:, -1] = 1
    basic_vars_list = [np.arange(m, m+n), np.arange(m)]
    return tableaus, basic_vars_list

In [126]:
def Lemke_Howson(A, B, init_pivot):
    tableaus, basic_vars_list = create_tableau(A, B)
    pivoting(tableaus[0], basic_vars_list[0], init_pivot)
    print(tableaus[0], basic_vars_list[0])
    flag = 1
    while True:
        pivot = np.setdiff1d(np.arange(sum(A.shape)), np.concatenate(basic_vars_list))
        if pivot:
            pivoting(tableaus[flag], basic_vars_list[flag], pivot[0])
            print(tableaus[flag], basic_vars_list[flag])
            flag = np.setdiff1d([0,1], flag)[0]
        else:
            break

In [127]:
Lemke_Howson(A, B_T.T, 1)

[[ 2.33333333  0.          2.66666667  1.         -0.33333333  0.66666667]
 [ 0.33333333  1.          0.16666667  0.          0.16666667  0.16666667]] [3 1]
[[ 1.          0.         -0.5         3.          0.          0.5       ]
 [ 0.          1.         -0.83333333  2.          0.          0.16666667]
 [ 0.          0.          0.16666667  0.          1.          0.16666667]] [0 1 4]
[[ 0.875   0.      1.      0.375  -0.125   0.25  ]
 [ 0.1875  1.      0.     -0.0625  0.1875  0.125 ]] [2 1]
[[ 1.         -1.5         0.75        0.          0.          0.25      ]
 [ 0.          0.5        -0.41666667  1.          0.          0.08333333]
 [ 0.          0.          0.16666667  0.          1.          0.16666667]] [0 3 4]


In [128]:
A = np.matrix(
    [[    9504,     -660,    19976,   -20526,     1776,    -8976],
     [ -111771,    31680,  -130944,   168124,    -8514,    52764],
     [  397584,  -113850,   451176,  -586476,    29216,  -178761],
     [  171204,   -45936,   208626,  -263076,    14124,   -84436],
     [ 1303104,  -453420,  1227336, -1718376,    72336,  -461736],
     [  737154,  -227040,   774576, -1039236,    48081,  -300036]]
)
B_T = np.matrix(
    [[   72336,  -461736,  1227336, -1718376,  1303104,  -453420],
     [   48081,  -300036,   774576, -1039236,   737154,  -227040],
     [   29216,  -178761,   451176,  -586476,   397584,  -113850],
     [   14124,   -84436,   208626,  -263076,   171204,   -45936],
     [    1776,    -8976,    19976,   -20526,     9504,     -660],
     [   -8514,    52764,  -130944,   168124,  -111771,    31680]]
)

In [129]:
Lemke_Howson(A, B_T.T, 1)

[[ -1.90235294e+04   0.00000000e+00   1.99747059e+05  -6.62494412e+05
    8.14207059e+05  -4.19468824e+05   1.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00  -5.14411765e+01   0.00000000e+00
   -5.04411765e+01]
 [ -1.12844118e+04   0.00000000e+00   1.06848824e+05  -3.53124265e+05
    4.19468824e+05  -2.04978529e+05   0.00000000e+00   1.00000000e+00
    0.00000000e+00   0.00000000e+00  -3.34264706e+01   0.00000000e+00
   -3.24264706e+01]
 [ -6.15382353e+03   0.00000000e+00   5.33451471e+04  -1.77691654e+05
    2.08307647e+05  -1.00705809e+05   0.00000000e+00   0.00000000e+00
    1.00000000e+00   0.00000000e+00  -1.99154412e+01   0.00000000e+00
   -1.89154412e+01]
 [ -2.58258824e+03   0.00000000e+00   2.07145098e+04  -6.99907353e+04
    8.18011765e+04  -3.97274706e+04   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.00000000e+00  -9.40686275e+00   0.00000000e+00
   -8.40686275e+00]
 [ -1.97860963e-01   1.00000000e+00  -2.22549020e+00   2.28676471e+00
   -1.0588