In [6]:
import numpy as np
from itertools import combinations

In [111]:
def Nondegenerate_Enumeration(A,B):
    NEs ={}
    M = np.arange(A.shape[0])
    N = np.arange(A.shape[1])
    K = np.min(A.shape)
    for k in np.arange(1,K+1,1):
        NEs[k] = []
        for I in combinations(range(A.shape[0]), k):
            for J in combinations(range(A.shape[1]), k):
                AIJ = A[I,:][:,J]
                BJI = B[I,:][:,J].getT()
                s1 = np.row_stack((np.c_[AIJ,-np.ones(AIJ.shape[0])],np.r_[np.ones(AIJ.shape[1]),[0]])).getI().dot(np.matrix(np.r_[np.zeros(AIJ.shape[0]),[1]]).getT())
                s2 = np.row_stack((np.c_[BJI,-np.ones(BJI.shape[0])],np.r_[np.ones(BJI.shape[1]),[0]])).getI().dot(np.matrix(np.r_[np.zeros(BJI.shape[0]),[1]]).getT())
                #Now let's check whether the solution satisfies NE
                if (s1[:-1]>0).all() & (s2[:-1]>0).all():
                    if (A[[i for i in M if i not in I],:][:,J].dot(s1[:-1])<=s1[-1]).all() & (B[I,:][:,[j for j in N if j not in J]].getT().dot(s2[:-1])<=s2[-1]).all():
                        xI = np.zeros(A.shape[0])
                        xI.flat[np.array(I)] = s2[:-1]
                        yJ = np.zeros(A.shape[1])
                        yJ.flat[np.array(J)] = s1[:-1]
                        NEs[k].append({'yJ':yJ,'u':s1[-1],'xI':xI,'v':s2[-1]})
                else:
                    continue
    return NEs

In [117]:
a = np.matrix([[3,3],[2,5],[0,6]])
b = np.matrix([[3,2],[2,6],[3,1]])

In [118]:
Nondegenerate_Enumeration(a,b)

[ 0.  0.  0.] (0,) [[ 1.]]
[ 0.  0.  0.] (0, 1) [[ 0.8]
 [ 0.2]]
[ 0.  0.  0.] (1, 2) [[ 0.33333333]
 [ 0.66666667]]


{1: [{'u': matrix([[ 3.]]),
   'v': matrix([[ 3.]]),
   'xI': array([ 1.,  0.,  0.]),
   'yJ': array([ 1.,  0.])}],
 2: [{'u': matrix([[ 3.]]),
   'v': matrix([[ 2.8]]),
   'xI': array([ 0.8,  0.2,  0. ]),
   'yJ': array([ 0.66666667,  0.33333333])},
  {'u': matrix([[ 4.]]),
   'v': matrix([[ 2.66666667]]),
   'xI': array([ 0.        ,  0.33333333,  0.66666667]),
   'yJ': array([ 0.33333333,  0.66666667])}]}